-- Migration: 006_create_ui_texts.sql
-- Create ui_texts table and seed all UI facing texts from database without fallbacks.

CREATE TABLE IF NOT EXISTS ui_texts (
    key VARCHAR(120) PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ui_texts_key ON ui_texts(key);

DROP TRIGGER IF EXISTS trg_ui_texts_updated_at ON ui_texts;
CREATE TRIGGER trg_ui_texts_updated_at
    BEFORE UPDATE ON ui_texts
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp_column();

-- Seed all UI-facing text
INSERT INTO ui_texts (key, value) VALUES
    ('app_skip_link', 'Lompat ke kolom pesan'),
    ('topbar_open_nav', 'Buka menu navigasi'),
    ('topbar_new_chat', 'Percakapan baru'),
    ('topbar_offline_badge', 'Mode offline'),
    ('topbar_theme_prefix', 'Beralih ke tema '),
    ('topbar_theme_light', 'terang'),
    ('topbar_theme_dark', 'gelap'),
    ('sidebar_aria_label', 'Bilah percakapan'),
    ('sidebar_brand_aria', 'Beranda Teach4All'),
    ('sidebar_brand_prefix', 'Teach'),
    ('sidebar_brand_number', '4'),
    ('sidebar_brand_suffix', 'All'),
    ('sidebar_close_button_aria', 'Tutup bilah samping'),
    ('sidebar_new_chat_button', 'Obrolan baru'),
    ('sidebar_quiz_aria', 'Buat kuis latihan'),
    ('sidebar_quiz_button', 'Kuis'),
    ('sidebar_quiz_draft', 'Buatkan kuis singkat 5 soal pilihan ganda tentang topik berikut: '),
    ('sidebar_material_aria', 'Pelajari materi baru'),
    ('sidebar_material_button', 'Materi'),
    ('sidebar_material_draft', 'Jelaskan ringkasan materi pembelajaran terstruktur mengenai topik berikut: '),
    ('sidebar_search_placeholder', 'Cari percakapan'),
    ('sidebar_search_aria', 'Cari percakapan'),
    ('sidebar_history_aria', 'Riwayat percakapan tersimpan'),
    ('sidebar_history_heading', 'Percakapan Anda'),
    ('sidebar_history_loading_aria', 'Memuat riwayat...'),
    ('sidebar_history_loading_text', 'Memuat riwayat...'),
    ('sidebar_empty_title', 'Awal yang baru'),
    ('sidebar_empty_desc', 'Percakapan Anda akan tersimpan di sini.'),
    ('sidebar_chat_options_aria_prefix', 'Opsi untuk '),
    ('sidebar_profile_avatar', 'A'),
    ('sidebar_profile_name', 'Ruang Kerja Anda'),
    ('sidebar_profile_detail', 'Pribadi · Tersimpan di server'),
    ('chat_welcome_eyebrow', 'RUANG UNTUK RASA INGIN TAHU'),
    ('chat_welcome_title_p1', 'Rasa ingin tahu.'),
    ('chat_welcome_title_p2', 'Dunia penuh '),
    ('chat_welcome_title_p3', 'kemungkinan.'),
    ('chat_welcome_desc_p1', 'Ajukan pertanyaan. Uraikan gagasan rumit. Pelajari hal baru.'),
    ('chat_welcome_desc_p2', 'Di mana pun Anda berada, ini tempat yang tepat untuk memulai.'),
    ('chat_copy_success', 'Tanggapan berhasil disalin.'),
    ('chat_copy_fail', 'Fitur salin tidak tersedia di peramban ini. Pilih teks tanggapan untuk menyalinnya.'),
    ('chat_loading_conversation_aria', 'Memuat percakapan...'),
    ('chat_loading_messages_text', 'Memuat pesan...'),
    ('chat_assistant_name', 'Teach4All'),
    ('chat_notice_label', 'Pemberitahuan'),
    ('chat_user_aria', 'Anda'),
    ('chat_typing_aria', 'Sedang mengetik tanggapan...'),
    ('chat_copy_button_aria', 'Salin tanggapan'),
    ('chat_composer_placeholder', 'Apa yang sedang Anda pikirkan?'),
    ('chat_composer_aria', 'Pesan Teach4All'),
    ('chat_composer_tools_aria', 'Alat percakapan'),
    ('chat_send_button_aria', 'Kirim pesan'),
    ('chat_suggestions_aria', 'Ide untuk memulai'),
    ('chat_suggestions_heading', 'Beberapa topik untuk memulai'),
    ('chat_prompt1_title', 'Jelaskan sederhana'),
    ('chat_prompt1_detail', 'Pahami konsep penting'),
    ('chat_prompt1_prompt', 'Jelaskan proses fotosintesis secara sederhana beserta contoh dalam kehidupan sehari-hari.'),
    ('chat_prompt2_title', 'Buat rencana belajar'),
    ('chat_prompt2_detail', 'Langkah kecil, hasil nyata'),
    ('chat_prompt2_prompt', 'Bantu saya membuat rencana belajar sederhana untuk minggu ini.'),
    ('chat_prompt3_title', 'Inspirasi ide kreatif'),
    ('chat_prompt3_detail', 'Kembangkan imajinasi Anda'),
    ('chat_prompt3_prompt', 'Berikan ide cerita kreatif atau topik menarik untuk memicu ide saya.'),
    ('chat_prompt4_title', 'Pecahkan masalah'),
    ('chat_prompt4_detail', 'Satu langkah demi satu langkah'),
    ('chat_prompt4_prompt', 'Tunjukkan langkah demi langkah cara menyelesaikan masalah atau soal ini.'),
    ('chat_offline_warning', 'Anda sedang offline. Tab ini tetap berfungsi, tetapi pemuatan ulang offline belum disiapkan.'),
    ('chat_messages_aria', 'Percakapan'),
    ('chat_footer_text', 'Belajar tanpa batas. Begitu pula potensi Anda.'),
    ('dialogs_tools_new_chat', 'Mulai percakapan baru'),
    ('dialogs_tools_export', 'Ekspor ruang kerja Anda'),
    ('dialogs_conversation_unavailable', 'Percakapan ini sudah tidak tersedia.'),
    ('dialogs_conversation_title_label', 'Nama percakapan'),
    ('dialogs_delete_button', 'Hapus'),
    ('dialogs_save_name_button', 'Simpan nama'),
    ('dialogs_clear_warning', 'Tindakan ini akan membersihkan semua percakapan dan draf pada sesi ini. Ekspor data terlebih dahulu jika Anda ingin menyimpannya.'),
    ('dialogs_delete_warning', 'Percakapan ini akan dihapus.'),
    ('dialogs_cancel_button', 'Batal'),
    ('dialogs_clear_confirm_button', 'Hapus semua data'),
    ('dialogs_delete_confirm_button', 'Hapus percakapan'),
    ('dialogs_title_tools', 'Alat percakapan'),
    ('dialogs_title_conversation', 'Opsi percakapan'),
    ('dialogs_title_clear', 'Hapus ruang kerja Anda?'),
    ('dialogs_title_delete', 'Hapus percakapan ini?'),
    ('dialogs_title_quiz', 'Daftar Kuis Pembelajaran'),
    ('dialogs_title_material', 'Daftar Materi Pembelajaran'),
    ('dialogs_quiz_desc', 'Pilih kuis latihan untuk menguji pemahaman Anda secara langsung.'),
    ('dialogs_material_desc', 'Pilih topik ringkasan materi terstruktur untuk dipelajari.'),
    ('dialogs_topic_custom_quiz', 'Atau ketik topik kuis kustom...'),
    ('dialogs_topic_custom_material', 'Atau ketik topik materi kustom...'),
    ('dialogs_topic_open_button', 'Buka'),
    ('dialogs_modules_count_suffix', 'modul'),
    ('dialogs_quiz_start_button', 'Mulai Kuis'),
    ('dialogs_material_open_button', 'Buka Materi'),
    ('dialogs_quiz_create_new', 'Buat Kuis Baru'),
    ('dialogs_material_create_new', 'Buat Materi Baru'),
    ('dialogs_meta_parts_suffix', 'Bagian'),
    ('dialogs_meta_read_time_suffix', 'mnt baca'),
    ('dialogs_meta_questions_suffix', 'Soal'),
    ('dialogs_meta_multiple_choice', 'Pilihan Ganda'),
    ('dialogs_meta_structured_logic', 'Logika Terarah'),
    ('dialogs_meta_applied_science', 'Sains Terapan'),
    ('dialogs_meta_self_reflection', 'Refleksi Diri'),
    ('dialogs_time_today', 'Hari ini'),
    ('dialogs_time_yesterday', 'Kemarin'),
    ('dialogs_time_days_ago_suffix', 'hari lalu'),
    ('dialogs_cat_biology', 'Biologi'),
    ('dialogs_cat_astronomy', 'Astronomi'),
    ('dialogs_cat_math', 'Matematika'),
    ('dialogs_cat_basic_science', 'Sains Dasar'),
    ('dialogs_cat_self_development', 'Pengembangan Diri'),
    ('dialogs_cat_literacy_science', 'Literasi & Sains'),
    ('dialogs_close_aria', 'Tutup dialog'),
    ('state_default_title', 'Percakapan baru'),
    ('state_offline_notice', 'Anda tampaknya sedang offline. Sambungkan kembali untuk mengirim pesan.'),
    ('state_max_chats_notice', 'Ruang kerja Anda memiliki 100 obrolan. Ekspor atau hapus percakapan lama untuk memberi ruang.'),
    ('state_send_failed', 'Gagal mengirim pesan. Silakan coba lagi.'),
    ('state_chat_deleted', 'Percakapan telah dihapus.'),
    ('state_workspace_cleared', 'Percakapan dan draf telah dibersihkan.'),
    ('state_export_success', 'Ekspor ruang kerja berhasil diunduh.'),
    ('offline_setup_failed', 'Pemasangan mode offline belum selesai. Percakapan Anda tetap tersimpan secara lokal; sambungkan kembali dan muat ulang untuk mencoba lagi.')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = CURRENT_TIMESTAMP;
