-- Migration: 010_add_mock_quiz_material_ui_texts.sql
-- Add UI texts for mock quiz and material cards, suffixes, categories, and timestamps

INSERT INTO ui_texts (key, value) VALUES
    ('dialogs_modules_count_suffix', 'modul'),
    ('dialogs_quiz_start_button', 'Mulai Kuis'),
    ('dialogs_material_open_button', 'Buka Materi'),
    ('dialogs_quiz_create_new', 'Buat Kuis Baru'),
    ('dialogs_material_create_new', 'Buat Materi Baru'),
    ('dialogs_meta_parts_suffix', 'Bagian'),
    ('dialogs_meta_read_time_suffix', 'mnt baca'),
    ('dialogs_meta_questions_suffix', 'Soal'),
    ('dialogs_meta_multiple_choice', 'Pilihan Ganda'),
    ('dialogs_meta_structured_logic', 'Logika Terarah'),
    ('dialogs_meta_applied_science', 'Sains Terapan'),
    ('dialogs_meta_self_reflection', 'Refleksi Diri'),
    ('dialogs_time_today', 'Hari ini'),
    ('dialogs_time_yesterday', 'Kemarin'),
    ('dialogs_time_days_ago_suffix', 'hari lalu'),
    ('dialogs_cat_biology', 'Biologi'),
    ('dialogs_cat_astronomy', 'Astronomi'),
    ('dialogs_cat_math', 'Matematika'),
    ('dialogs_cat_basic_science', 'Sains Dasar'),
    ('dialogs_cat_self_development', 'Pengembangan Diri'),
    ('dialogs_cat_literacy_science', 'Literasi & Sains'),
    ('dialogs_mock_quiz_1_title', 'Kuis Fotosintesis & Reaksi Terang'),
    ('dialogs_mock_quiz_1_summary', 'Evaluasi 5 soal tentang kloroplas, penyerapan foton matahari, siklus Calvin, dan pelepasan oksigen.'),
    ('dialogs_mock_quiz_1_prompt', 'Buatkan kuis singkat 5 soal pilihan ganda tentang topik berikut: Fotosintesis dan Reaksi Terang'),
    ('dialogs_mock_quiz_2_title', 'Kuis Tata Surya & Karakteristik Planet'),
    ('dialogs_mock_quiz_2_summary', 'Uji pemahaman tentang planet kebumian, planet gas raksasa, orbit elips, dan gravitasi Matahari.'),
    ('dialogs_mock_quiz_2_prompt', 'Buatkan kuis singkat 5 soal pilihan ganda tentang topik berikut: Tata Surya dan Karakteristik Planet'),
    ('dialogs_mock_quiz_3_title', 'Kuis Penalaran Matematika & Logika'),
    ('dialogs_mock_quiz_3_summary', 'Soal penalaran proporsional, pola deret angka, dan pemecahan masalah bertahap.'),
    ('dialogs_mock_quiz_3_prompt', 'Buatkan kuis singkat 5 soal pilihan ganda tentang topik berikut: Matematika dan Logika Bertahap'),
    ('dialogs_mock_quiz_4_title', 'Kuis Pengetahuan Sains & Alam Sekitar'),
    ('dialogs_mock_quiz_4_summary', 'Pertanyaan seputar wujud zat, siklus air, perubahan energi, dan gaya gesek di lingkungan sekitar.'),
    ('dialogs_mock_quiz_4_prompt', 'Buatkan kuis singkat 5 soal pilihan ganda tentang topik berikut: Sains dan Alam Sekitar'),
    ('dialogs_mock_quiz_5_title', 'Kuis Metode & Manajemen Waktu Belajar'),
    ('dialogs_mock_quiz_5_summary', 'Refleksi penerapan teknik active recall, spaced repetition, dan strategi fokus pomodoro.'),
    ('dialogs_mock_quiz_5_prompt', 'Buatkan kuis singkat 5 soal pilihan ganda tentang topik berikut: Rencana dan Metode Belajar'),
    ('dialogs_mock_mat_1_title', 'Ringkasan Fotosintesis: Dapur Bertenaga Surya'),
    ('dialogs_mock_mat_1_summary', 'Uraian terstruktur tentang struktur daun, konversi foton menjadi glukosa, dan peran krusial klorofil.'),
    ('dialogs_mock_mat_1_prompt', 'Jelaskan ringkasan materi pembelajaran terstruktur mengenai topik berikut: Fotosintesis'),
    ('dialogs_mock_mat_2_title', 'Arsitektur Tata Surya & Hukum Gravitasi'),
    ('dialogs_mock_mat_2_summary', 'Susunan planet dalam dan planet luar, pengaruh orbit elips Kepler, serta karakteristik sabuk asteroid.'),
    ('dialogs_mock_mat_2_prompt', 'Jelaskan ringkasan materi pembelajaran terstruktur mengenai topik berikut: Tata Surya'),
    ('dialogs_mock_mat_3_title', 'Kerangka 5 Langkah Pemecahan Masalah Matematika'),
    ('dialogs_mock_mat_3_summary', 'Langkah terarah membedah soal rumit: pemahaman premis, pembuatan model, penyelesaian, dan validasi.'),
    ('dialogs_mock_mat_3_prompt', 'Jelaskan ringkasan materi pembelajaran terstruktur mengenai topik berikut: Pemecahan Masalah Matematika'),
    ('dialogs_mock_mat_4_title', 'Strategi Belajar Efektif & Retensi Memori'),
    ('dialogs_mock_mat_4_summary', 'Panduan active recall, teknik Feynman sederhana, dan cara mengatasi kurva lupa Ebbinghaus secara konsisten.'),
    ('dialogs_mock_mat_4_prompt', 'Jelaskan ringkasan materi pembelajaran terstruktur mengenai topik berikut: Rencana dan Metode Belajar'),
    ('dialogs_mock_mat_5_title', 'Prinsip Berpikir Kritis & Literasi Informasi'),
    ('dialogs_mock_mat_5_summary', 'Tiga pilar verifikasi argumen ilmiah, pengujian data, dan pembedaan kausalitas dari korelasi semu.'),
    ('dialogs_mock_mat_5_prompt', 'Jelaskan ringkasan materi pembelajaran terstruktur mengenai topik berikut: Sains dan Pemikiran Kritis')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = CURRENT_TIMESTAMP;
