// Deliberately local and deterministic. This is not an AI model or a request queue.
export function createReply(input) {
  const text = input.toLowerCase();
  let reply;
  if (/kuis|quiz/.test(text)) {
    reply = 'Berikut adalah kuis singkat 5 soal untuk menguji pemahaman Anda:\n\n1. Apa fungsi utama klorofil pada daun dalam proses fotosintesis?\n   A. Menyerap air\n   B. Menangkap energi cahaya matahari\n   C. Melepaskan karbon dioksida\n   D. Menyimpan cadangan glukosa\n\n2. Manakah di bawah ini yang merupakan produk hasil dari fotosintesis?\n   A. Oksigen dan Glukosa\n   B. Karbon dioksida dan Air\n   C. Nitrogen dan Hidrogen\n   D. Metana dan Ozon\n\n3. Di bagian manakah klorofil paling banyak ditemukan dalam sel tumbuhan?\n   A. Dinding sel\n   B. Vakuola\n   C. Kloroplas\n   D. Inti sel\n\n4. Gas apa yang diserap oleh tumbuhan dari udara untuk proses fotosintesis?\n   A. Karbon monoksida\n   B. Karbon dioksida\n   C. Helium\n   D. Nitrogen\n\n5. Mengapa tanaman tetap membutuhkan air meskipun sudah mendapatkan sinar matahari yang cukup?\n   A. Untuk memberikan warna hijau pada batang\n   B. Sebagai bahan baku donor elektron dan hidrogen dalam fotosintesis\n   C. Untuk membunuh mikroorganisme di tanah\n   D. Sebagai pengganti gas oksigen\n\nTuliskan jawaban Anda (misal: 1A, 2B, dst.) untuk melihat pembahasannya!';
  } else if (/materi|material/.test(text)) {
    reply = 'Berikut adalah ringkasan materi terstruktur yang siap Anda pelajari:\n\n📌 Konsep Pokok:\nSetiap proses pembelajaran menjadi lebih mudah ketika kita membaginya ke dalam unit-unit kecil yang saling berhubungan.\n\n📖 3 Pilar Pemahaman:\n1. Definisi & Hakikat: Memahami mengapa konsep ini ada dan fungsi dasarnya.\n2. Hubungan Sebab-Akibat: Bagaimana komponen-komponen di dalamnya saling berinteraksi satu sama lain.\n3. Contoh Praktis: Mengamati bagaimana konsep ini diterapkan dalam kehidupan sehari-hari.\n\n💡 Tips Penguasaan Cepat:\nSetelah membaca konsep, luangkan 2 menit untuk menuliskannya kembali tanpa melihat catatan. Topik materi apa lagi yang ingin Anda eksplorasi lebih dalam?';
  } else if (/photosynth|fotosintesis|plants? (make|grow)|tanaman|tumbuhan|sunlight|cahaya matahari/.test(text)) {
    reply = 'Bayangkan daun sebagai dapur bertenaga surya (solar-powered kitchen) mini.\n\nTumbuhan menyerap energi dari sinar matahari untuk mengubah air dan karbon dioksida menjadi gula (glukosa). Gula ini menjadi sumber energi bagi pertumbuhannya, sementara oksigen dilepaskan ke udara. Proses menakjubkan ini disebut fotosintesis (photosynthesis).\n\nCoba ini: gambarlah sehelai daun. Beri tanda panah untuk sinar matahari, air, dan karbon dioksida yang masuk, serta glukosa dan oksigen yang keluar.\n\nPertanyaan menarik untuk dipikirkan: mengapa tanaman tumbuh lebih lambat di dalam ruangan yang gelap?';
  } else if (/plan|study|routine|schedule|rencana|belajar|jadwal/.test(text)) {
    reply = 'Berikut adalah rencana belajar terstruktur yang dapat Anda terapkan dengan mudah:\n\n1. Tetapkan satu tujuan jelas: Tentukan konsep apa yang ingin Anda pahami hari ini.\n2. Pelajari materi selama 15–20 menit: Gunakan buku, catatan, atau referensi yang Anda miliki.\n3. Tutup catatan Anda: Luangkan 5 menit untuk menjelaskan kembali konsep tersebut dengan bahasa Anda sendiri.\n4. Evaluasi pemahaman: Cari tahu bagian mana yang belum Anda mengerti dan tuliskan satu pertanyaan penting.\n5. Ulangi esok hari: Belajar secara bertahap setiap hari jauh lebih efektif daripada belajar semalaman.\n\nMari mulai: hal apa yang paling ingin Anda pelajari minggu ini?';
  } else if (/write|story|inspir|creativ|ideas|cerita|kreatif|menulis|ide/.test(text)) {
    reply = 'Latihan kreativitas singkat: temukan keajaiban dari hal-hal sederhana di sekitar Anda.\n\nMulailah dengan kalimat pembuka ini: “Jalan setapak itu biasanya selalu berakhir di sini. Namun hari ini, jalan itu terus memanjang menembus kabut.”\n\nPilihlah seorang tokoh, beri mereka tujuan yang ingin dicapai, dan sertakan satu peristiwa yang tidak terduga. Tuliskan kelanjutannya selama 5 menit tanpa perlu mengedit.\n\nJika merasa buntu, lihatlah sekeliling Anda dan masukkan tiga benda pertama yang Anda lihat ke dalam cerita. Ide hebat tidak membutuhkan awal yang sempurna!';
  } else if (/math|solve|problem|step|matematika|pecahkan|masalah|soal|langkah/.test(text)) {
    reply = 'Mari kita susun langkah terstruktur untuk memecahkan masalah ini:\n\n1. Pahami pertanyaan: Apa inti masalah yang sedang dicari atau diselesaikan?\n2. Tuliskan informasi yang diketahui: Catat angka, fakta, serta kondisi yang ditentukan.\n3. Buat sketsa atau model sederhana: Visualisasi seringkali membantu memperjelas solusi.\n4. Kerjakan langkah demi langkah secara runtut dan logis.\n5. Periksa kembali jawaban Anda dengan pertanyaan yang semula diajukan.\n\nSebagai contoh: jika 3 buku berharga 12 koin, maka harga 1 buku adalah 12 ÷ 3 = 4 koin. Lima buku akan berharga 5 × 4 = 20 koin.\n\nTuliskan soal atau masalah Anda, dan langkah pertama apa yang ingin Anda coba?';
  } else if (/explain|learn|understand|teach|jelaskan|pahami|ajari/.test(text)) {
    reply = 'Salah satu cara terbaik untuk benar-benar memahami suatu gagasan adalah dengan menjelaskannya secara sederhana.\n\nCoba siklus belajar berikut ini:\n\n1. Tuliskan apa yang sudah Anda ketahui tentang topik tersebut.\n2. Jelaskan kembali seolah-olah Anda sedang mengajar teman sebaya.\n3. Beri tanda pada bagian yang masih sulit Anda terangkan dengan lancar. Bagian itulah yang perlu Anda pelajari kembali.\n4. Hubungkan konsep tersebut dengan analogi atau kejadian nyata sehari-hari.\n\nAnda dapat mencoba mengetik “Jelaskan fotosintesis” untuk melihat contoh penjelasan konsep yang ramah dan intuitif.';
  } else {
    reply = 'Anda memiliki ruang belajar mandiri di sini, bahkan ketika tanpa koneksi internet. Pendamping luring ini memiliki beberapa panduan topik bawaan untuk membantu Anda.\n\nCoba minta saya untuk menjelaskan fotosintesis, membuat rencana belajar, memberikan ide cerita kreatif, menyusun kuis, atau memecahkan masalah langkah demi langkah.\n\nAnda juga dapat menggunakan ruang ini sebagai buku catatan pribadi yang siap menemani proses belajar Anda.';
  }
  return reply;
}
