export const SEED_QUIZ_QUESTIONS = {
  '00000000-0000-0000-0001-000000000001': [
    {
      questionNumber: 1,
      questionText: 'Di bagian manakah pada sel tumbuhan reaksi terang fotosintesis berlangsung?',
      options: [
        { id: 0, text: 'Membran tilakoid dalam kloroplas' },
        { id: 1, text: 'Stroma kloroplas' },
        { id: 2, text: 'Matriks mitokondria' },
        { id: 3, text: 'Vakuola sentral' },
      ],
      correctAnswer: 0,
      explanation: 'Reaksi terang berlangsung pada membran tilakoid kloroplas di mana terdapat klorofil dan fotosistem I & II.',
      points: 10,
    },
    {
      questionNumber: 2,
      questionText: 'Senyawa gas apakah yang dihasilkan sebagai produk sampingan dari fotolisis air?',
      options: [
        { id: 0, text: 'Karbon dioksida (CO2)' },
        { id: 1, text: 'Oksigen (O2)' },
        { id: 2, text: 'Gas nitrogen (N2)' },
        { id: 3, text: 'Gas metana (CH4)' },
      ],
      correctAnswer: 1,
      explanation: 'Fotolisis air memecah molekul H2O menjadi elektron, ion hidrogen, dan gas oksigen bebas.',
      points: 10,
    },
    {
      questionNumber: 3,
      questionText: 'Molekul energi utama yang dihasilkan selama reaksi terang untuk digunakan dalam siklus Calvin adalah...',
      options: [
        { id: 0, text: 'ATP dan NADPH' },
        { id: 1, text: 'Glukosa dan FADH2' },
        { id: 2, text: 'Asam piruvat dan NADH' },
        { id: 3, text: 'ADP dan NADP+' },
      ],
      correctAnswer: 0,
      explanation: 'ATP dan NADPH dihasilkan melalui fosforilasi dan transfer elektron untuk menyuplai energi di siklus Calvin.',
      points: 10,
    },
    {
      questionNumber: 4,
      questionText: 'Enzim krusial yang mengikat karbon dioksida pada awal siklus Calvin dinamakan...',
      options: [
        { id: 0, text: 'ATP Sintase' },
        { id: 1, text: 'RuBisCO' },
        { id: 2, text: 'Katalase' },
        { id: 3, text: 'Amilase' },
      ],
      correctAnswer: 1,
      explanation: 'RuBisCO (Ribulose-1,5-bisphosphate carboxylase-oxygenase) mengkatalisis fiksasi CO2 pada RuBP.',
      points: 10,
    },
    {
      questionNumber: 5,
      questionText: 'Faktor lingkungan yang dapat membatasi laju fotosintesis pada siang hari terik adalah...',
      options: [
        { id: 0, text: 'Penutupan stomata karena dehidrasi' },
        { id: 1, text: 'Kelebihan kadar nitrogen udara' },
        { id: 2, text: 'Ketiadaan klorofil' },
        { id: 3, text: 'Penurunan intensitas cahaya' },
      ],
      correctAnswer: 0,
      explanation: 'Saat terik dan kering, stomata menutup untuk mencegah penguapan air, sehingga pasokan CO2 menurun.',
      points: 10,
    },
  ],
  '00000000-0000-0000-0001-000000000002': [
    {
      questionNumber: 1,
      questionText: 'Planet manakah yang memiliki massa dan ukuran terbesar di tata surya kita?',
      options: [
        { id: 0, text: 'Saturnus' },
        { id: 1, text: 'Yupiter' },
        { id: 2, text: 'Uranus' },
        { id: 3, text: 'Neptunus' },
      ],
      correctAnswer: 1,
      explanation: 'Yupiter adalah planet terbesar dengan massa lebih dari 2.5 kali gabungan seluruh planet lainnya.',
      points: 10,
    },
    {
      questionNumber: 2,
      questionText: 'Sabuk asteroid utama di tata surya terletak di antara orbit planet...',
      options: [
        { id: 0, text: 'Bumi dan Mars' },
        { id: 1, text: 'Mars dan Yupiter' },
        { id: 2, text: 'Yupiter dan Saturnus' },
        { id: 3, text: 'Saturnus dan Uranus' },
      ],
      correctAnswer: 1,
      explanation: 'Sabuk asteroid terletak di antara Mars dan Yupiter, memisahkan planet kebumian dan planet luar.',
      points: 10,
    },
    {
      questionNumber: 3,
      questionText: 'Hukum Kepler I menyatakan bahwa lintasan orbit planet mengelilingi Matahari berbentuk...',
      options: [
        { id: 0, text: 'Lingkaran sempurna' },
        { id: 1, text: 'Elips dengan Matahari di salah satu fokusnya' },
        { id: 2, text: 'Parabola terbuka' },
        { id: 3, text: 'Spiral konvergen' },
      ],
      correctAnswer: 1,
      explanation: 'Hukum I Kepler membuktikan bahwa semua planet bergerak dalam orbit elips dengan Matahari di salah satu fokusnya.',
      points: 10,
    },
    {
      questionNumber: 4,
      questionText: 'Planet yang dikenal memiliki efek rumah kaca ekstrem dengan suhu permukaan terpanas adalah...',
      options: [
        { id: 0, text: 'Merkurius' },
        { id: 1, text: 'Venus' },
        { id: 2, text: 'Mars' },
        { id: 3, text: 'Yupiter' },
      ],
      correctAnswer: 1,
      explanation: 'Atmosfer tebal CO2 di Venus memerangkap panas ekstrem hingga mencapai suhu rata-rata lebih dari 460°C.',
      points: 10,
    },
    {
      questionNumber: 5,
      questionText: 'Benda langit yang mengelilingi Matahari dan memiliki ekor yang selalu menjauhi Matahari adalah...',
      options: [
        { id: 0, text: 'Meteorit' },
        { id: 1, text: 'Komet' },
        { id: 2, text: 'Asteroid' },
        { id: 3, text: 'Satelit alami' },
      ],
      correctAnswer: 1,
      explanation: 'Angin matahari mendorong partikel es dan gas yang menguap dari komet sehingga ekornya selalu menjauhi Matahari.',
      points: 10,
    },
  ],
  '00000000-0000-0000-0001-000000000003': [
    {
      questionNumber: 1,
      questionText: 'Tentukan bilangan berikutnya pada deret pola: 3, 7, 15, 31, 63, ...',
      options: [
        { id: 0, text: '127' },
        { id: 1, text: '125' },
        { id: 2, text: '119' },
        { id: 3, text: '131' },
      ],
      correctAnswer: 0,
      explanation: 'Pola deret adalah dikali 2 lalu ditambah 1: (63 × 2) + 1 = 127.',
      points: 10,
    },
    {
      questionNumber: 2,
      questionText: 'Jika 5 pekerja membutuhkan 12 hari untuk menyelesaikan proyek, berapa hari yang dibutuhkan 10 pekerja?',
      options: [
        { id: 0, text: '24 hari' },
        { id: 1, text: '6 hari' },
        { id: 2, text: '4 hari' },
        { id: 3, text: '8 hari' },
      ],
      correctAnswer: 1,
      explanation: 'Perbandingan berbalik nilai: (5 × 12) / 10 = 6 hari.',
      points: 10,
    },
    {
      questionNumber: 3,
      questionText: 'Premis 1: Semua mamalia bernapas dengan paru-paru. Premis 2: Lumba-lumba adalah mamalia. Kesimpulannya adalah...',
      options: [
        { id: 0, text: 'Lumba-lumba bernapas dengan insang' },
        { id: 1, text: 'Lumba-lumba bernapas dengan paru-paru' },
        { id: 2, text: 'Beberapa mamalia tidak bernapas dengan paru-paru' },
        { id: 3, text: 'Lumba-lumba bukan ikan' },
      ],
      correctAnswer: 1,
      explanation: 'Berdasarkan silogisme kategoris sah, lumba-lumba bernapas dengan paru-paru.',
      points: 10,
    },
    {
      questionNumber: 4,
      questionText: 'Sebuah segitiga siku-siku memiliki sisi alas 6 cm dan tinggi 8 cm. Berapakah sisi miringnya?',
      options: [
        { id: 0, text: '9 cm' },
        { id: 1, text: '10 cm' },
        { id: 2, text: '12 cm' },
        { id: 3, text: '14 cm' },
      ],
      correctAnswer: 1,
      explanation: 'Berdasarkan teorema Pythagoras: akar(6^2 + 8^2) = akar(100) = 10 cm.',
      points: 10,
    },
    {
      questionNumber: 5,
      questionText: 'Dua koin seimbang dilempar bersamaan. Berapakah peluang munculnya minimal satu sisi gambar?',
      options: [
        { id: 0, text: '1/4' },
        { id: 1, text: '1/2' },
        { id: 2, text: '3/4' },
        { id: 3, text: '2/3' },
      ],
      correctAnswer: 2,
      explanation: 'Ruang sampel total 4: (A,A), (A,G), (G,A), (G,G). 3 di antaranya memiliki minimal satu sisi G. Peluang = 3/4.',
      points: 10,
    },
  ],
  '00000000-0000-0000-0001-000000000004': [
    {
      questionNumber: 1,
      questionText: 'Peristiwa perubahan wujud zat dari padat langsung menjadi gas tanpa melalui fase cair disebut...',
      options: [
        { id: 0, text: 'Mengembun' },
        { id: 1, text: 'Menyublim' },
        { id: 2, text: 'Mengkristal' },
        { id: 3, text: 'Membeku' },
      ],
      correctAnswer: 1,
      explanation: 'Menyublim adalah perubahan wujud dari padat langsung ke gas.',
      points: 10,
    },
    {
      questionNumber: 2,
      questionText: 'Energi yang tersimpan pada benda karena posisi atau ketinggiannya adalah...',
      options: [
        { id: 0, text: 'Energi kinetik' },
        { id: 1, text: 'Energi potensial gravitasi' },
        { id: 2, text: 'Energi kalor' },
        { id: 3, text: 'Energi kimia' },
      ],
      correctAnswer: 1,
      explanation: 'Energi potensial gravitasi dirumuskan dengan Ep = m × g × h.',
      points: 10,
    },
    {
      questionNumber: 3,
      questionText: 'Dalam siklus air, proses penguapan air dari permukaan tanaman ke atmosfer dinamakan...',
      options: [
        { id: 0, text: 'Evaporasi' },
        { id: 1, text: 'Transpirasi' },
        { id: 2, text: 'Presipitasi' },
        { id: 3, text: 'Kondensasi' },
      ],
      correctAnswer: 1,
      explanation: 'Transpirasi adalah pelepasan uap air dari stomata tumbuhan ke atmosfer.',
      points: 10,
    },
    {
      questionNumber: 4,
      questionText: 'Bunyi hukum aksi-reaksi Newton (Hukum III Newton) menyatakan bahwa...',
      options: [
        { id: 0, text: 'Gaya total sebanding dengan massa' },
        { id: 1, text: 'Setiap gaya aksi menimbulkan gaya reaksi yang sama besar dan berlawanan arah' },
        { id: 2, text: 'Benda diam akan selalu diam' },
        { id: 3, text: 'Percepatan berbanding terbalik dengan gaya' },
      ],
      correctAnswer: 1,
      explanation: 'Hukum III Newton: F_aksi = -F_reaksi bekerja pada dua benda berbeda secara simultan.',
      points: 10,
    },
    {
      questionNumber: 5,
      questionText: 'Perambatan kalor yang terjadi tanpa memerlukan medium perantara adalah...',
      options: [
        { id: 0, text: 'Konduksi' },
        { id: 1, text: 'Konveksi' },
        { id: 2, text: 'Radiasi' },
        { id: 3, text: 'Adveksi' },
      ],
      correctAnswer: 2,
      explanation: 'Radiasi termal merambat melalui gelombang elektromagnetik tanpa medium perantara.',
      points: 10,
    },
  ],
  '00000000-0000-0000-0001-000000000005': [
    {
      questionNumber: 1,
      questionText: 'Metode mengingat dengan cara aktif menguji diri sendiri (tanpa melihat buku) disebut...',
      options: [
        { id: 0, text: 'Passive re-reading' },
        { id: 1, text: 'Active recall' },
        { id: 2, text: 'Cramming' },
        { id: 3, text: 'Highlighting' },
      ],
      correctAnswer: 1,
      explanation: 'Active recall merangsang memori kerja untuk menarik kembali informasi dari ingatan jangka panjang.',
      points: 10,
    },
    {
      questionNumber: 2,
      questionText: 'Teknik Pomodoro standar membagi interval belajar menjadi sesi fokus selama...',
      options: [
        { id: 0, text: '25 menit fokus, 5 menit istirahat' },
        { id: 1, text: '50 menit fokus, 20 menit istirahat' },
        { id: 2, text: '60 menit fokus tanpa henti' },
        { id: 3, text: '10 menit fokus, 10 menit istirahat' },
      ],
      correctAnswer: 0,
      explanation: 'Siklus standar Pomodoro adalah 25 menit fokus intensif diikuti jeda istirahat 5 menit.',
      points: 10,
    },
    {
      questionNumber: 3,
      questionText: 'Kurva Lupa Ebbinghaus menunjukkan bahwa manusia paling banyak melupakan informasi baru pada...',
      options: [
        { id: 0, text: '24 jam pertama setelah mempelajari informasi' },
        { id: 1, text: 'Satu bulan setelah belajar' },
        { id: 2, text: 'Saat sedang tidur malam' },
        { id: 3, text: 'Satu minggu setelah belajar' },
      ],
      correctAnswer: 0,
      explanation: 'Penurunan retensi memori terjadi paling drastis dalam 24 jam pertama.',
      points: 10,
    },
    {
      questionNumber: 4,
      questionText: 'Kunci utama dari Teknik Feynman dalam memahami konsep rumit adalah...',
      options: [
        { id: 0, text: 'Menghafal definisi kata demi kata' },
        { id: 1, text: 'Menjelaskan konsep dengan bahasa sederhana seolah mengajarkannya pada anak kecil' },
        { id: 2, text: 'Menggarisbawahi seluruh teks dengan stabilo' },
        { id: 3, text: 'Membaca buku secara cepat' },
      ],
      correctAnswer: 1,
      explanation: 'Teknik Feynman menyederhanakan bahasa dan membuat analogi konkret.',
      points: 10,
    },
    {
      questionNumber: 5,
      questionText: 'Manfaat menerapkan Spaced Repetition (pengulangan berjeda) adalah...',
      options: [
        { id: 0, text: 'Mempersingkat total waktu belajar sebelum ujian dengan SKS' },
        { id: 1, text: 'Mengubah ingatan jangka pendek menjadi ingatan jangka panjang yang kokoh' },
        { id: 2, text: 'Menghindari perlunya membuat ringkasan' },
        { id: 3, text: 'Menghilangkan kebutuhan tidur malam' },
      ],
      correctAnswer: 1,
      explanation: 'Spaced repetition menginterupsi kurva lupa pada interval yang tepat.',
      points: 10,
    },
  ],
};

export const SEED_MATERIAL_SECTIONS = {
  '00000000-0000-0000-0002-000000000001': [
    {
      sectionNumber: 1,
      title: '1. Pengantar Fotosintesis & Kloroplas',
      content: 'Fotosintesis adalah proses biokimia di mana organisme autotrof (tumbuhan hijau, alga, dan beberapa bakteri) mengonversi energi foton cahaya matahari menjadi glukosa.\n\nOrganel utama penyelenggara fotosintesis pada sel tumbuhan adalah kloroplas. Di dalamnya terdapat tilakoid (tempat reaksi terang) dan stroma (tempat siklus Calvin).',
      readTimeMinutes: 1,
    },
    {
      sectionNumber: 2,
      title: '2. Mekanisme Reaksi Terang & Fotolisis Air',
      content: 'Reaksi terang berlangsung bergantung langsung pada cahaya di membran tilakoid.\n\nFoton diserap oleh Fotosistem II dan I. Terjadi fotolisis air (pemecahan H2O menghasilkan gas O2). Aliran elektron memompa proton dan menggerakkan enzim ATP Sintase untuk menghasilkan ATP dan NADPH.',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 3,
      title: '3. Siklus Calvin (Reaksi Gelap) & Pembentukan Gula',
      content: 'Siklus Calvin berlangsung di stroma tanpa memerlukan cahaya langsung, memanfaatkan energi ATP dan NADPH dari reaksi terang.\n\nFase terdiri dari: Fiksasi Karbon oleh enzim RuBisCO, Reduksi 3-PGA menjadi G3P, dan Regenerasi RuBP untuk membentuk glukosa.',
      readTimeMinutes: 1,
    },
  ],
  '00000000-0000-0000-0002-000000000002': [
    {
      sectionNumber: 1,
      title: '1. Anatomi Pusat Tata Surya & Pengelompokan Planet',
      content: 'Matahari menguasai lebih dari 99,8% massa total tata surya. Planet dikelompokkan menjadi:\n- Planet Kebumian (Terestrial): Merkurius, Venus, Bumi, dan Mars.\n- Planet Gas & Es Raksasa (Jovian): Yupiter, Saturnus, Uranus, dan Neptunus.',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 2,
      title: '2. Sabuk Asteroid & Wilayah Trans-Neptunus',
      content: 'Di antara orbit Mars dan Yupiter terbentang Sabuk Asteroid Utama. Di luar orbit Neptunus terdapat Sabuk Kuiper dan Awan Oort yang menjadi asal komet berperiode panjang.',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 3,
      title: '3. Hukum Kepler & Gravitasi Universal Newton',
      content: 'Hukum I Kepler: Orbit berbentuk elips dengan Matahari di salah satu fokus.\nHukum II Kepler: Garis khayal menyapu luas daerah yang sama dalam selang waktu yang sama.\nHukum III Kepler: Kuadrat periode sebanding dengan pangkat tiga jarak rata-rata.',
      readTimeMinutes: 2,
    },
  ],
  '00000000-0000-0000-0002-000000000003': [
    {
      sectionNumber: 1,
      title: '1. Kerangka Berpikir George Pólya',
      content: 'Empat pilar pemecahan masalah Pólya:\n1. Memahami Masalah (identifikasi premis dan hal yang ditanyakan).\n2. Menyusun Rencana (pola, analogi, model persamaan).\n3. Melaksanakan Rencana (eksekusi teliti langkah demi langkah).\n4. Memeriksa Kembali (validasi hasil dan substitusi).',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 2,
      title: '2. Strategi Dekonstruksi & Pemodelan Aljabar',
      content: 'Tentukan variabel dengan simbol yang jelas. Terjemahkan kalimat narasi ke notasi aljabar, dan eliminasi informasi distraktor.',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 3,
      title: '3. Verifikasi Logika & Validasi Batasan',
      content: 'Lakukan sanity check: periksa kesesuaian satuan, keabsahan nilai riil (tidak negatif bila mengukur kuantitas objek), dan pastikan seluruh batasan terpenuhi.',
      readTimeMinutes: 1,
    },
  ],
  '00000000-0000-0000-0002-000000000004': [
    {
      sectionNumber: 1,
      title: '1. Menaklukkan Kurva Lupa Hermann Ebbinghaus',
      content: 'Tanpa tinjauan ulang aktif, otak melupakan hingga 70% informasi dalam 24 jam. Spaced Repetition (pengulangan berjeda pada hari 1, hari 3, 1 minggu, dan 1 bulan) mengubah retensi menjadi ingatan jangka panjang permanen.',
      readTimeMinutes: 1,
    },
    {
      sectionNumber: 2,
      title: '2. Active Recall vs Ilusi Penguasaan Pasif',
      content: 'Membaca ulang pasif menciptakan ilusi kompetensi. Active recall menguji pemanggilan memori secara mandiri dengan menutup buku dan menuliskan intisari konsep.',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 3,
      title: '3. Implementasi Teknik Feynman 4 Langkah',
      content: 'Pilih konsep -> Ajarkan kepada pemula tanpa istilah rumit -> Temukan titik macet pemahaman -> Buka referensi dan sederhanakan dengan analogi nyata.',
      readTimeMinutes: 1,
    },
  ],
  '00000000-0000-0000-0002-000000000005': [
    {
      sectionNumber: 1,
      title: '1. Tiga Pilar Skeptisisme Ilmiah yang Sehat',
      content: 'Pilar nalar kritis: Keterbukaan terhadap bukti baru (open-mindedness), tuntutan bukti sebanding dengan bobot klaim, dan prinsip falsifiabilitas hipotesis.',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 2,
      title: '2. Menghindari Jebakan Kausalitas vs Korelasi',
      content: 'Korelasi tidak selalu berarti hubungan sebab-akibat (Cum hoc ergo propter hoc). Selalu periksa kemungkinan adanya faktor variabel perancu (confounding variable).',
      readTimeMinutes: 2,
    },
    {
      sectionNumber: 3,
      title: '3. Panduan Praktis Verifikasi Informasi Digital',
      content: 'Terapkan teknik Lateral Reading: buka tab baru untuk memeriksa kredibilitas sumber, afiliasi penulis, dan verifikasi silang independen.',
      readTimeMinutes: 1,
    },
  ],
};
